### ISSUE TITLE
[Bug] Not able to get --watch to work in examples/debug-webpack4 (or my own project)

### ISSUE THREAD

**Issue by schickm** [sysgears/mochapack#39] opened 2019-11-04 20:05 UTC
- [ x ] I'd be willing to submit the fix (if I knew how to fix it...)

**Describe the bug**

I recently tried to switch over a code-base that was using `mocha-webpack` to use `mochapack`.  I noticed `--watch` stopped working when I made the switch.  In order to double check that the problem wasn't our usage, I cloned the `mochapack` repo and ran the test loop...all tests passed (including the watch test)...  

However, I then opened up the `examples/debug-webpack4` folder and ran the test loop in watch mode.  Making changes to the `index.test.js` file _did not_ cause the test loop to re-run.

Now maybe the example just hasn't been updated to account for some change, or maybe there is an actual bug - I'm not really sure.  

**To Reproduce**

1. checkout `master` (git sha 7d0cbaff91b4f0b91b3e27afb342a92bea567df3 at time of filing)
2. Run `cd examples/debug-webpack4 && npm i && npm run test:watch`
3. Observe that test loop runs successfully and waits
4. Open up the file `examples/debug-webpack4/src/__tests__/index.test.js` and make a change to it
5.  Observe that the test loop _DOES NOT_ re-run.

**Environment if relevant (please complete the following information):**

 - OS: OSX 10.14.16
 - Node version: 11.9.0
 - Mochapack version: git sha 7d0cbaff91b4f0b91b3e27afb342a92bea567df3 (master at time of filing

**Comment by larixer** [comment] 2019-11-05 16:57
Hm, I have OS X `10.14.6`, btw does `10.14.16` even exist? My node version is 12.12.0, but I had node 10.x as well. I don't observe that test loop not re-runs. It does re-run for me

**Comment by schickm** [comment] 2019-11-06 15:19
Sorry about that, `10.14.6`, was correct.  I must have made a typo.  

I switched over to use node version 12.12.0, but I still can't get the test loop to re-run.  I'll have some other co-workers double check it on their machines...but so far the problem sounds like it might just be me!

**Comment by schickm** [comment] 2019-11-06 15:20
Any tips about how I might go about debugging this issue?  Areas of the code to set breakpoints in?

**Comment by larixer** [comment] 2019-11-06 15:33
@schickm Have you tried running `webpack-dev-server` in that folder and making a change to `src/index.js`, does it runs the compilation after your change?

**Comment by larixer** [comment] 2019-11-06 15:34
@schickm Or even more relevant test would be to run `webpack --watch` in that folder and change `src/index.js`, will it trigger re-compilation?

**Comment by schickm** [comment] 2019-11-06 18:25
@larixer Yep, both `webpack-dev-server` and `webpack --watch` will trigger re-compilation when I change `src/index.js`

The plot thickens...  

Thanks for being so responsive 😃

**Comment by schickm** [comment] 2019-11-06 18:27
I also ran both commands by calling directly into `./node_modules/.bin/` (which is effectively what `npx` does) and achieved the same results.  Just wanted to call that out as well.

**Comment by larixer** [comment] 2019-11-06 18:41
@schickm There is a script called `test:watch:debug` in `xamples/debug-webpack4/package.json`, so you can run `npm test:watch:debug` and then attach the debugger, step in several times until it loads full node modules tree and then place breakpoint here and see if it enters:
https://github.com/sysgears/mochapack/blob/master/src/runner/TestRunner.js#L221

**Comment by larixer** [comment] 2019-11-06 18:44
@schickm I wonder where the condition in the `if` right there is truthy for you?
https://github.com/sysgears/mochapack/blob/master/src/runner/TestRunner.js#L223

**Comment by larixer** [comment] 2019-11-06 18:59
@schickm I have published `mochapack@1.1.6` with source maps (previously they were not published), it should provide better experience when you try to debug `mochapack` source code

**Comment by schickm** [comment] 2019-11-06 21:46
Thanks for publishing that, that was very helpful. 

`fileAddedOrDeleted` does get triggered, and `matchesGlob` does evaluate to `true` when I move/add/delete a file.  However, when I modify the contents of an existing file, `fileAddedOrDeleted` does not get triggered.  That seems to be expected since chokidar is being used to only listen for `add` and `unlink` events. 

Does `mochapack` rely on `webpack` to know when files get modified?  I'm guessing maybe here in [this call to registerReadyCallback()](https://github.com/sysgears/mochapack/blob/e016731940fca967bcf39fb082eca7daa8d05aa9/src/runner/TestRunner.js#L188-L196)?

I should mention that `mochapack` has always re-run the test loop when I add/remove files, it's just re-running when files are modified that isn't working for me.

**Comment by schickm** [comment] 2019-11-06 21:55
I've had two different co-workers try as well, both experienced the same issue I'm having with `--watch`.  Both were using OS X 10.14.6 & Node 12.13.0.  Additionally I was able to repro it on another machine running OSX 10.13.6 (High Sierra) and Node 11.14.0.

Don't know if that helps or not 🤷‍♂

**Comment by larixer** [comment] 2019-11-07 05:44
@schickm Looks like some dependencies changed their behaviour. When you opened the ticket, I have checked `examples/debug-webpack4` with `yarn`. I use `yarn` in this repo, all projects has `yarn.lock`. When I first checked the issue didn't reproduce for me, because `examples/debug-webpack4/yarn.lock` pointed to older versions. Then you asked about debugger, I noticed that there are no sourcemaps, I released new `mochapack`, with sourcemaps and I dropped and regenerated `examples/debug-webpack4/yarn.lock`. With new `yarn.lock` the problem started to reproduce for me too, since new versions of dependencies started to be used. If I rollback to previous version of `yarn.lock` the problem does not reproduce.

I'm trying to figure out now which dependencies changed their watch behaviour.

**Comment by larixer** [comment] 2019-11-07 05:58
@schickm So yeah, its `chokidar`. When I force usage of `chokidar@2.1.6` via `package.json -> resolutions` yarn option, the problem no longer reproduces. `mochapack` didn't change anything in this regard. The same problem will be present with `mocha-webpack` as well if it will be used with recent `chokidar` version. I'm looking how to fix it so that new `chokidar` worked too...

**Comment by larixer** [comment] 2019-11-07 07:49
@schickm This is not really a problem of `mochapack`. It is rather broken concepts in `node_modules` and the behaviour of `chokidar`. Looks like multiple versions of `chokidar` conflict with each another. But `chokidar` authors cannot mark in their `package.json` that `chokidar` must be a singleton in a project. There is a workaround to this, that libraries that use `chokidar` can mark it as a `peerDependency`, but `webpack-dev-server`, `watchpack`  and `mochapack` do not mark `chokidar` as a `peerDependency`. All of them should. And after that it will be the responsibility of `webpack-dev-server`, `watchpack` and `mochapack` consumers to install single version of `chokidar`. 

For now I have released `mochapack@1.1.8` that uses exactly the same version of `chokidar` as the latest versions of `webpack-dev-server` and `watchpack`, e.g. `2.1.8` and the problem does not reproduce for me.

But in the future releases of `mochapack` I will probably have to shift the responsibility to have single chokidar version in the project to the users, by declaring chokidar as a peer dependency.

**Comment by schickm** [comment] 2019-11-07 16:36
Fascinating, looks like you were a major version ahead.  I pulled down your updates and indeed everything works as it should!

Sorry to have overlooked the `yarn` thing...I forgot that I could have totally different dependencies since I was running `npm i`.

Thanks again for being so responsive during this whole process.  Now I can transition us from `mocha-webpack` to `mochapack`, and we'll have a little more following for this library.

**Comment by schickm** [comment] 2019-11-07 16:37
I be sure to keep an eye out for the `peerDependencies` change.

**Comment by larixer** [comment] 2019-11-07 16:46
@schickm The great idea about fixing `peerDependencies` concept with possibility of responsibility shift to the author is explained here by @arcanis:
https://github.com/yarnpkg/berry/issues/417
Hopefully it will be released in Yarn 2.1 and will help relieve the pains of having singleton packages in JS ecosystem.

**Closed** 2019-11-07 17:55 UTC
Labels: bug
