### ISSUE TITLE
[Bug]

### ISSUE THREAD

**Issue by BobbieBarker** [sysgears/mochapack#24] opened 2019-08-07 23:18 UTC
- [x] I'd be willing to submit the fix
maybe.
**Describe the bug**

I attempt to run the test suit and I receive this error:
`Error: ENOENT: no such file or directory, chdir '.tmp/mochapack/1565219434941'`
**To Reproduce**
I just attempt to run this from the terminal 
`"test": "mochapack --bail --timeout 8000 --exit --recursive --webpack-config webpack.config.test.js",`

The _minimal_ information needed to reproduce your issue (ideally a very minimal project setup published on GitHub).
Note that bugs without minimal reproductions might be closed.

**Screenshots**

**Environment if relevant (please complete the following information):**

 - OS: [e.g. OSX, Linux, Windows, ...]
OSX
 - Node version [e.g. 8.15.0, 10.15.1, ...]
10.5
 - Mochapack version [e.g. 1.1.3, ...]
5.2
 - Webpack version [e.g. 4.26.1, ...]
4.38
**Additional context**

my webpack config:
```
'use strict';

const nodeExternals = require('webpack-node-externals');
const DotenvFlow = require('dotenv-flow-webpack');

module.exports = {
  entry: './polarity.js',
  mode: 'development',
  target: 'node',
  devtool: 'inline-cheap-module-source-map',
  node: {
    __dirname: false
  },
  resolve: {
    extensions: ['.ts', '.js']
  },
  module: {
    rules: [
      { test: /\.ts$/, use: ['ts-loader'] },
      { test: /\.js$/, use: ['source-map-loader'], enforce: 'pre' }
    ]
  },
  externals: [nodeExternals()],
  plugins: [new DotenvFlow()]
};
```

**Comment by vlasenko** [comment] 2019-08-08 08:41
@BobbieBarker I was unable to reproduce this issue, while using your `webpack.config.js` in this project:
https://github.com/sysgears/mochapack/tree/master/examples/debug-webpack4
Please note that FULL reproduction example is needed. Obviously your info is incomplete in this regard.

**Comment by vlasenko** [comment] 2019-08-20 13:18
Closing this issue as the reproduction example is incomplete. Feel free to reopen it with full reproduction example.

**Closed by vlasenko** 2019-08-20 13:18 UTC
Labels: bug, no reproduction
